# Site settings
author: Serena Dinh 
title: Serena Dinh 
header-img: img/home-bg.png
email: heyserenadinh@gmail.com
copyright_name: Serena Dinh 
description: > # this means to ignore newlines until "baseurl:"
  My journey to Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  serenadinh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
